package whois

import (
	"regexp"
	"time"
)

type ExpiryRe struct {
	Re     *regexp.Regexp
	Format string
}

var stdWhoisRe = regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+Z)`)

// TODO: make better regex for la,lb,ke,my,gl,mu

var WhoisExpiryMap = map[string]ExpiryRe{
	"ac": {Re: stdWhoisRe, Format: time.RFC3339},
	"af": {Re: stdWhoisRe, Format: time.RFC3339},
	"ag": {Re: stdWhoisRe, Format: time.RFC3339},
	"am": {Re: regexp.MustCompile(`Expires:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"ar": {Re: regexp.MustCompile(`expire:\s*(\d+-\d+-\d+ \d+:\d+:\d+)`), Format: "2006-01-02 15:04:05"},
	"ax": {Re: regexp.MustCompile(`expires\.+:\s(\d+\.\d+\.\d+)`), Format: "01-02-2006"},
	"bh": {Re: stdWhoisRe, Format: time.RFC3339},
	"bi": {Re: stdWhoisRe, Format: time.RFC3339},
	"bj": {Re: stdWhoisRe, Format: time.RFC3339},
	"bm": {Re: stdWhoisRe, Format: time.RFC3339},
	"bn": {Re: regexp.MustCompile(`Expiration Date:\s*(\d+-\w+-\d+ \d+:\d+:\d+)`), Format: "02-Jan-2006 15:04:05"},
	"bo": {Re: regexp.MustCompile(`Fecha de corte: (\d+-\d+-\d+)`), Format: "2006-01-02"},
	"br": {Re: regexp.MustCompile(`expires:\s*(\d+)`), Format: "20060102"},
	"bz": {Re: stdWhoisRe, Format: time.RFC3339},
	"ca": {Re: stdWhoisRe, Format: time.RFC3339},
	"cc": {Re: stdWhoisRe, Format: time.RFC3339},
	"ci": {Re: stdWhoisRe, Format: time.RFC3339},
	"cl": {Re: regexp.MustCompile(`Expiration date: (\d+-\d+-\d+ \d+:\d+:\d+)`), Format: "2006-01-02 15:04:05"},
	"cm": {Re: stdWhoisRe, Format: time.RFC3339},
	"cn": {Re: regexp.MustCompile(`Expiration Time: ([\d\-]+ [\d\-:]+)`), Format: "2006-01-02 15:04:05"},
	"co": {Re: stdWhoisRe, Format: time.RFC3339},
	"cr": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"cx": {Re: stdWhoisRe, Format: time.RFC3339},
	"cz": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"dk": {Re: regexp.MustCompile(`Expires:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"dm": {Re: stdWhoisRe, Format: time.RFC3339},
	"do": {Re: stdWhoisRe, Format: time.RFC3339},
	"ee": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "2006.01.02"},
	"fi": {Re: regexp.MustCompile(`expires\.+:\s(\d+\.\d+\.\d+ \d+:\d+:\d+)`), Format: "2.1.2006 15:04:05"},
	"fm": {Re: stdWhoisRe, Format: time.RFC3339},
	"fo": {Re: stdWhoisRe, Format: time.RFC3339},
	"fr": {Re: regexp.MustCompile(`Expiry\s*Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"gd": {Re: stdWhoisRe, Format: time.RFC3339},
	"ge": {Re: regexp.MustCompile(`Registry Expiry Date:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"gh": {Re: stdWhoisRe, Format: time.RFC3339},
	"gl": {Re: regexp.MustCompile(`Registry Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"gs": {Re: stdWhoisRe, Format: time.RFC3339},
	"gy": {Re: stdWhoisRe, Format: time.RFC3339},
	"hk": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+)`), Format: "02-01-2006"},
	"hn": {Re: stdWhoisRe, Format: time.RFC3339},
	"hr": {Re: regexp.MustCompile(`Registrar Registration Expiration Date: (\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"ht": {Re: stdWhoisRe, Format: time.RFC3339},
	"id": {Re: regexp.MustCompile(`Expiration Date:\s*(\d+-\d+-\d+ \d+:\d+:\d+)`), Format: "2006-01-02 15:04:05"},
	"ie": {Re: stdWhoisRe, Format: time.RFC3339},
	"in": {Re: stdWhoisRe, Format: time.RFC3339},
	"io": {Re: stdWhoisRe, Format: time.RFC3339},
	"is": {Re: regexp.MustCompile(`expires:\s*(\w+  \w+ \w+)`), Format: "January  2 2006"},
	"it": {Re: regexp.MustCompile(`Expire Date:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"jp": {Re: regexp.MustCompile(`\[有効期限\]\s*(\d+\/\d+\/\d+)`), Format: "2006/01/02"},
	"la": {Re: regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"kg": {Re: regexp.MustCompile(`Record expires on: \w+ (\w+ \d+ \d+:\d+:\d+ \d+)`), Format: "Jan 2 15:04:05 2006"},
	"kn": {Re: stdWhoisRe, Format: time.RFC3339},
	"kr": {Re: regexp.MustCompile(`Expiration Date\s*: (\d+\. \d+\. \d+).`), Format: "2006. 01. 02"},
	"kw": {Re: stdWhoisRe, Format: time.RFC3339},
	"ky": {Re: stdWhoisRe, Format: time.RFC3339},
	"ke": {Re: regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"lb": {Re: regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"ls": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"lt": {Re: regexp.MustCompile(`Expires:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"ly": {Re: stdWhoisRe, Format: time.RFC3339},
	"ma": {Re: stdWhoisRe, Format: time.RFC3339},
	"md": {Re: regexp.MustCompile(`Expires\s*on:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"me": {Re: stdWhoisRe, Format: time.RFC3339},
	"mg": {Re: stdWhoisRe, Format: time.RFC3339},
	"mk": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"mn": {Re: stdWhoisRe, Format: time.RFC3339},
	"mr": {Re: stdWhoisRe, Format: time.RFC3339},
	"mu": {Re: regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"mw": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"mx": {Re: regexp.MustCompile(`Expiration Date:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"my": {Re: regexp.MustCompile(`Registry Expiry Date: (\d+-\d+-\d+T\d+:\d+:\d+)\.?`), Format: "2006-01-02T15:04:05"},
	"mz": {Re: stdWhoisRe, Format: time.RFC3339},
	"nf": {Re: stdWhoisRe, Format: time.RFC3339},
	"ng": {Re: stdWhoisRe, Format: time.RFC3339},
	"nu": {Re: regexp.MustCompile(`expires:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"om": {Re: stdWhoisRe, Format: time.RFC3339},
	"pf": {Re: regexp.MustCompile(`Expire\s*\(JJ\/MM\/AAAA\)\s*:\s*(\d+\/\d+\/\d+)`), Format: "02/01/2006"},
	"pl": {Re: regexp.MustCompile(`renewal date:\s*(\d+\.\d+\.\d+ \d+:\d+:\d+)`), Format: "2006.01.02 15:04:05"},
	"pm": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"pr": {Re: stdWhoisRe, Format: time.RFC3339},
	"pt": {Re: regexp.MustCompile(`Expiration Date:\s*(\d+\/\d+\/\d+ \d+:\d+:\d+)`), Format: "02/01/2006 15:04:05"},
	"pw": {Re: stdWhoisRe, Format: time.RFC3339},
	"re": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"ro": {Re: regexp.MustCompile(`Expires\s*On:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"rs": {Re: regexp.MustCompile(`Expiration\s*date:\s*(\d+\.\d+\.\d+ \d+:\d+:\d+)`), Format: "02.01.2006 15:04:05"},
	"ru": {Re: regexp.MustCompile(`free-date:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"rw": {Re: stdWhoisRe, Format: time.RFC3339},
	"sb": {Re: stdWhoisRe, Format: time.RFC3339},
	"sd": {Re: stdWhoisRe, Format: time.RFC3339},
	"se": {Re: regexp.MustCompile(`expires:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"sg": {Re: regexp.MustCompile(`Expiration Date:\s*(\d+-\w+-\d+ \d+:\d+:\d+)`), Format: "02-Jan-2006 15:04:05"},
	"sh": {Re: stdWhoisRe, Format: time.RFC3339},
	"si": {Re: regexp.MustCompile(`expire:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"sk": {Re: regexp.MustCompile(`Valid\s*Until:\s*(\d*-\d*-\d*)`), Format: "2006-01-02"},
	"sl": {Re: stdWhoisRe, Format: time.RFC3339},
	"sn": {Re: regexp.MustCompile(`Date\s*d'expiration:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"so": {Re: stdWhoisRe, Format: time.RFC3339},
	"ss": {Re: stdWhoisRe, Format: time.RFC3339},
	"st": {Re: regexp.MustCompile(`expiration-date:\s*(\d+-\d+-\d+ \d+:\d+:\d+)`), Format: "2006-01-02 15:04:05"},
	"su": {Re: regexp.MustCompile(`free-date:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"sx": {Re: stdWhoisRe, Format: time.RFC3339},
	"sy": {Re: stdWhoisRe, Format: time.RFC3339},
	"tc": {Re: stdWhoisRe, Format: time.RFC3339},
	"td": {Re: stdWhoisRe, Format: time.RFC3339},
	"tf": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"tg": {Re: regexp.MustCompile(`Expiration:\.+(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"th": {Re: regexp.MustCompile(`Exp\s*date:\s*(\d+ \w+ \d+)`), Format: "2 Jan 2006"},
	"tm": {Re: regexp.MustCompile(`Expiry\s*:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"tr": {Re: regexp.MustCompile(`Expires\s*on\.*:\s*(\d+-\w+-\d+).`), Format: "2006-Jan-02"},
	"tw": {Re: regexp.MustCompile(`Record\s*expires\s*on\s*(\d+-\d+-\d+ \d+:\d+:\d+)`), Format: "2006-01-02 15:04:05"},
	"tz": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"ua": {Re: regexp.MustCompile(`expires:\s*(\d+-\d+-\d+ \d+:\d+:\d+.\d+)`), Format: "2006-01-02 15:04:05-07"},
	"ug": {Re: regexp.MustCompile(`Expires\s*On:\s*(\d+-\d+-\d+)`), Format: "2006-01-02"},
	"uk": {Re: regexp.MustCompile(`Expiry\s*date:\s*(\d+-\w+-\d+)`), Format: "02-Jan-2006"},
	"us": {Re: stdWhoisRe, Format: time.RFC3339},
	"uz": {Re: regexp.MustCompile(`Expiration\s*Date:\s*(\d+-\w+-\d+)`), Format: "02-Jan-2006"},
	"ve": {Re: regexp.MustCompile(`expire:\s*(\d+\.\d+\.\d+)`), Format: "02.01.2006"},
	"vg": {Re: stdWhoisRe, Format: time.RFC3339},
	"vu": {Re: stdWhoisRe, Format: time.RFC3339},
	"wf": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"ws": {Re: stdWhoisRe, Format: time.RFC3339},
	"yt": {Re: regexp.MustCompile(`Expiry Date:\s*(\d+-\d+-\d+T\d+:\d+:\d+Z)`), Format: time.RFC3339},
	"zm": {Re: stdWhoisRe, Format: time.RFC3339},
}
